{# ************ Autogenerated file: do not edit ************ #}
page('/photos/construction-industrielle/', function(ctx, next) { app.loadAlbum('/photos/x/album/construction-industrielle/', 'Construction industrielle') } );
page('/photos/transformation-et-amenagm/', function(ctx, next) { app.loadAlbum('/photos/x/album/transformation-et-amenagm/', 'Amenagement de container') } );
page('/photos/mobilier-urbain/', function(ctx, next) { app.loadAlbum('/photos/x/album/mobilier-urbain/', 'Mobilier urbain') } );
page('/photos/transformation-vehicules/', function(ctx, next) { app.loadAlbum('/photos/x/album/transformation-vehicules/', 'Amenagement de vehicule') } );
page('/photos/construction-navale/', function(ctx, next) { app.loadAlbum('/photos/x/album/construction-navale/', 'Construction navale') } );
page('/photos/chantier-naval/', function(ctx, next) { app.loadAlbum('/photos/x/album/chantier-naval/', 'Chantier naval') } );
page('/photos/evenementiel/', function(ctx, next) { app.loadAlbum('/photos/x/album/evenementiel/', 'Evénementiel') } );
page('/photos/nos-navires/', function(ctx, next) { app.loadAlbum('/photos/x/album/nos-navires/', 'Nos navires') } );
page('/photos/communication-et-publicit/', function(ctx, next) { app.loadAlbum('/photos/x/album/communication-et-publicit/', 'Communication et publicité') } );